<?php
session_start();

if (!isset($_SESSION['Admin_User'])) {
    header("Location: login.php");
    exit;
}

$servername = "localhost";
$username = "root";
$password = "";
$database = "payrollsystem";

$conn = new mysqli($servername, $username, $password, $database);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$date_from = $_POST['date_from'] ?? '';
$date_to = $_POST['date_to'] ?? '';
$employee_id = $_POST['employee_id'] ?? 'all';

if (empty($date_from) || empty($date_to)) {
    die("Date range is required");
}

if ($employee_id && $employee_id != 'all') {
    $query = "
        SELECT p.*, e.first_name, e.last_name, e.position, sm.site_name
        FROM payroll p
        LEFT JOIN employees e ON e.id = p.employee_id
        LEFT JOIN site_employee se ON e.id = se.employee_id
        LEFT JOIN site_monitoring sm ON se.site_id = sm.id
        WHERE p.employee_id = ?
        AND ((p.date_from BETWEEN ? AND ?) OR (p.date_to BETWEEN ? AND ?))
        ORDER BY p.date_from DESC
    ";
    $stmt = $conn->prepare($query);
    $stmt->bind_param("issss", $employee_id, $date_from, $date_to, $date_from, $date_to);
} else {
    $query = "
        SELECT p.*, e.first_name, e.last_name, e.position, sm.site_name
        FROM payroll p
        LEFT JOIN employees e ON e.id = p.employee_id
        LEFT JOIN site_employee se ON e.id = se.employee_id
        LEFT JOIN site_monitoring sm ON se.site_id = sm.id
        WHERE (p.date_from BETWEEN ? AND ?) OR (p.date_to BETWEEN ? AND ?)
        ORDER BY e.first_name, e.last_name
    ";
    $stmt = $conn->prepare($query);
    $stmt->bind_param("ssss", $date_from, $date_to, $date_from, $date_to);
}

$stmt->execute();
$result = $stmt->get_result();

$employees = [];
$total_gross = 0;
$total_deductions = 0;
$total_net = 0;

while ($row = $result->fetch_assoc()) {

    $employees[] = [
        'id' => str_pad($row['employee_id'], 4, '0', STR_PAD_LEFT),
        'name' => $row['first_name'] . ' ' . $row['last_name'],
        'position' => $row['position'],
        'site' => $row['site_name'] ?? 'Not Assigned',
        'from' => date('M d, Y', strtotime($row['date_from'])),
        'to' => date('M d, Y', strtotime($row['date_to'])),
        'hours' => $row['total_work_hours'],
        'gross' => $row['base_salary'],
        'deductions' => $row['total_deductions'],
        'net' => $row['net_pay'],
        'status' => ucfirst($row['status'] ?? 'Pending')
    ];

    $total_gross += $row['base_salary'];
    $total_deductions += $row['total_deductions'];
    $total_net += $row['net_pay'];
}

$period_desc = date('F d, Y', strtotime($date_from)) . " to " . date('F d, Y', strtotime($date_to));

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=Salary_Report_" . date('Y-m-d') . ".xls");

echo "
<html>
<head>
<meta charset='UTF-8'>
<style>
body { font-family: Arial; font-size: 14px; }

table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    border: 1px solid black;
    padding: 8px;
    vertical-align: middle;
}

th {
    background-color: #e6e6e6;
    font-weight: bold;
    text-align: center;
    font-size: 15px;
}

.title {
    font-size: 18px;
    font-weight: bold;
    text-align: center;
}

.section {
    background-color: #d9d9d9;
    font-weight: bold;
    font-size: 15px;
}

.center { text-align: center; }
.right { text-align: right; }
.left { text-align: left; }

</style>
</head>
<body>

<table>

<tr>
<td colspan='11' class='title'>JLC BEST Construction, OPC - OFFICIAL SALARY REPORT</td>
</tr>

<tr><td colspan='11'></td></tr>

<!-- SINGLE ROW GENERATED DETAILS -->
<tr>
<td colspan='4'><b>Generated On:</b> ".date('F d, Y h:i A')."</td>
<td colspan='3'><b>Generated By:</b> ".$_SESSION['Admin_User']."</td>
<td colspan='4'><b>Report Period:</b> ".$period_desc."</td>
</tr>

<tr><td colspan='11'></td></tr>

<!-- EXECUTIVE SUMMARY SINGLE ROW FORMAT -->
<tr><td colspan='11' class='section'>EXECUTIVE SUMMARY</td></tr>

<tr>
<th>Total Records</th>
<th>Total Gross</th>
<th>Total Deductions</th>
<th>Total Net Payroll</th>
<th colspan='7'></th>
</tr>

<tr>
<td class='center'>".count($employees)."</td>
<td class='right'>₱".number_format($total_gross,2)."</td>
<td class='right'>₱".number_format($total_deductions,2)."</td>
<td class='right'>₱".number_format($total_net,2)."</td>
<td colspan='7'></td>
</tr>

<tr><td colspan='11'></td></tr>

<!-- DETAILED PAYROLL -->
<tr><td colspan='11' class='section'>DETAILED PAYROLL REPORT</td></tr>

<tr>
<th width='6%'>ID</th>
<th width='16%'>Employee Name</th>
<th width='12%'>Position</th>
<th width='12%'>Site</th>
<th width='10%'>From</th>
<th width='10%'>To</th>
<th width='8%'>Hours</th>
<th width='10%'>Base Salary</th>
<th width='10%'>Deductions</th>
<th width='10%'>Net Pay</th>
<th width='6%'>Status</th>
</tr>";

foreach ($employees as $emp) {
    echo "<tr>
    <td class='center'>{$emp['id']}</td>
    <td class='left'>{$emp['name']}</td>
    <td class='left'>{$emp['position']}</td>
    <td class='left'>{$emp['site']}</td>
    <td class='center'>{$emp['from']}</td>
    <td class='center'>{$emp['to']}</td>
    <td class='center'>{$emp['hours']}</td>
    <td class='right'>₱".number_format($emp['gross'],2)."</td>
    <td class='right'>₱".number_format($emp['deductions'],2)."</td>
    <td class='right'>₱".number_format($emp['net'],2)."</td>
    <td class='center'>{$emp['status']}</td>
    </tr>";
}

echo "
<tr>
<td colspan='7' class='right'><b>GRAND TOTAL</b></td>
<td class='right'><b>₱".number_format($total_gross,2)."</b></td>
<td class='right'><b>₱".number_format($total_deductions,2)."</b></td>
<td class='right'><b>₱".number_format($total_net,2)."</b></td>
<td></td>
</tr>

<tr><td colspan='11'></td></tr>

<tr>
<td colspan='11' class='center'>
This is a computer-generated document. No signature is required.
</td>
</tr>

</table>
</body>
</html>";

exit;
?>